#!/bin/sh

set -eu

readonly command_name="install"
dotfilesdir="$(dirname -- "$0")"
readonly dotfilesdir

readonly config_files="${dotfilesdir}/config-files"
readonly mypy_cache="${config_files}/.local/bin/.mypy_cache"

if [ -e "$mypy_cache" ]
then
	rm -r -- "$mypy_cache"
fi

cd -- "$config_files"
tar --create --file=- . | (cd -- ~ && tar --extract --file=-)

printf '%s: Installation successful.\n' "$command_name"
